import { DataType } from '../index'

export const data: DataType[] = [
  {
    key: '1',
    id: '00001',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '2',
    id: '00002',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: '管理者',
    status: '未ログイン',
  },
  {
    key: '3',
    id: '00003',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: '管理者',
    status: '無効',
  },
  {
    key: '4',
    id: '00004',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '5',
    id: '00005',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '6',
    id: '00006',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '7',
    id: '00007',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '8',
    id: '00008',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '9',
    id: '00009',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '10',
    id: '00010',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '11',
    id: '00011',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '12',
    id: '00012',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '13',
    id: '00013',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '14',
    id: '00014',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '15',
    id: '00015',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '16',
    id: '00016',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '17',
    id: '00017',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '18',
    id: '00018',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '19',
    id: '00019',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
  {
    key: '20',
    id: '00020',
    registrationDate: '2022/01/30',
    fullName: 'ユーザ氏名',
    emailAddress: 'xxxxxxxxxxxxxx@xxxxxxxxxx.xxx',
    authority: 'オペレーター',
    status: '有効',
  },
]
