export const data = [
  {
    key: '1',
    id: '00001',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: 'ＮＴＴドコモ',
    numberOfContract: 12,
    isHasPersonalInformation: true,
    isHasTermsOfService: false,
    locale: {
      code: 'jp',
      name: '日本',
    },
    status: '有効',
  },
  {
    key: '2',
    id: '00002',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: 'トヨタ自動車',
    numberOfContract: 13,
    isHasPersonalInformation: false,
    isHasTermsOfService: false,
    locale: {
      code: 'jp',
      name: '日本',
    },
    status: '有効',
  },
  {
    key: '3',
    id: '00003',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: '三菱ＵＦＪフィナンシャル・グループ',
    numberOfContract: 17,
    isHasPersonalInformation: false,
    isHasTermsOfService: true,
    locale: {
      code: 'tw',
      name: '臺灣',
    },
    status: '有効',
  },
  {
    key: '4',
    id: '00004',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: 'ソニー',
    numberOfContract: 15,
    isHasPersonalInformation: true,
    isHasTermsOfService: true,
    locale: {
      code: 'my',
      name: 'マレーシア',
    },
    status: '有効',
  },
  {
    key: '5',
    id: '00005',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: 'ファーストリテイリング',
    numberOfContract: 11,
    isHasPersonalInformation: true,
    isHasTermsOfService: false,
    locale: {
      code: 'jp',
      name: '日本',
    },
    status: '有効',
  },
  {
    key: '6',
    id: '00006',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: 'ソフトバンク',
    numberOfContract: 1,
    isHasPersonalInformation: true,
    isHasTermsOfService: true,
    locale: {
      code: 'th',
      name: 'タイ',
    },
    status: '有効',
  },
  {
    key: '7',
    id: '00007',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: '任天堂',
    numberOfContract: 2,
    isHasPersonalInformation: false,
    isHasTermsOfService: false,
    locale: {
      code: 'vn',
      name: 'ベトナム',
    },
    status: '有効',
  },
  {
    key: '8',
    id: '00008',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: 'ホンダ',
    numberOfContract: 9,
    isHasPersonalInformation: true,
    isHasTermsOfService: false,
    locale: {
      code: 'jp',
      name: '日本',
    },
    status: '有効',
  },
  {
    key: '9',
    id: '00009',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: 'オリエンタルランド	',
    numberOfContract: 10,
    isHasPersonalInformation: false,
    isHasTermsOfService: false,
    locale: {
      code: 'cn',
      name: '中国',
    },
    status: '有効',
  },
  {
    key: '10',
    id: '000010',
    dateStart: '2022/01/01',
    dateEnd: '2022/12/12',
    organizationName: '三菱商事',
    numberOfContract: 12,
    isHasPersonalInformation: false,
    isHasTermsOfService: true,
    locale: {
      code: 'jp',
      name: '日本',
    },
    status: '有効',
  },
]
